kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-volume
  namespace: [ENV_NAME]
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi