kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-volume
  namespace: [ENV_NAME]
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pg/storage"