apiVersion: v1
kind: Service
metadata:
  name: eazybe-api-s
  namespace: default
spec:
  type: NodePort
  ports:
  - name: app
    port: 3000
    nodePort: 30000
    protocol: TCP
    targetPort: app-ez
  selector:
    app: eazybe-api
    # type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eazybe-api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eazybe-api
    spec:
      containers:
      - image: eazybestartup/eazybe-api:latest
        name: eazybe-api
        ports:
        - containerPort: 3000
          name: app-ez
          protocol: TCP
        env:
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: reg-mm
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Sao_Paulo