apiVersion: v1
kind: Service
metadata:
  name: tag-s
  namespace: [ENV_NAME] 
spec:
  ports:
  - name: app
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: tag

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tag
  namespace: [ENV_NAME] 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tag
    spec:
      containers:
      - image: docker.mmcafe.com.br/tag:latest
        name: tag
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: database
        - name: POSTGRES_DB
          value: tagdb
        - name: JWT_KEY
          value: [JWT_AMBIENTE]-859826D718C2CA1DB42FD554515FD9AA2675E33
        - name: KAFKA_HOST
          value: kafka://bootstrap:9092
        - name: ELASTIC_HOST
          value: elasticsearch-s
        - name: ELASTIC_CLUSTER_NAME
          value: docker-cluster
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: reg-mm
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Sao_Paulo