apiVersion: v1
kind: Service
metadata:
 name: load-balance
 annotations:
   service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
   service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "hou02"
  #  service.kubernetes.io/ibm-load-balancer-cloud-provider-vlan: "<vlan_id>"
spec:
 type: LoadBalancer
 selector:
   app: nginx
 ports:
  - protocol: TCP
    port: 80
#  loadBalancerIP: 184.172.234.75
 externalIPs:
  - 184.172.234.75