apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: router
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io: /
spec:
  rules:
  - host: ezapi.mmcafe.com.br
    http:
      paths:
      - path: /eazybe
        backend:
          serviceName: eazybe-api-s
          servicePort: 3000