apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: [ENV_NAME]
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: [ENV_NAME]
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pg-volume
        - mountPath: /etc/localtime
          name: tz-config
#        lifecycle:
#          postStart:
#            exec:
#              command: ["usr/bin/psql", "-U postgres -tc", "\"SELECT 1 FROM pg_database WHERE datname = 'licensedb'\" | grep -q 1 || psql -U postgres -c \"CREATE DATABASE licensedb\""]
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: pg-volume
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Sao_Paulo


